#!/bin/bash
##SBATCH -A loni_virus2023    ### Allocation name
#SBATCH -A loni_virus24    ### Allocation name
#SBATCH -p single             ### Queue name
#SBATCH -t 5-00:00:00         ### Wall time
#SBATCH -N 1                  ### Number of nodes
##SBATCH -n 1                 ### Number of tasks
#SBATCH -c 8                  ### Number of cores per task
#SBATCH --output=slurm-%j.out-%N
#SBATCH --error=slurm-%j.err-%N
#SBATCH -J multiqc            ### Job name

## Load conda module
module load conda

## Activate the MultiQC conda environment
source activate multiqc-py3

# Check if conda environment activated successfully
if [[ $? -ne 0 ]]; then
    echo "Error: Conda environment activation failed"
    exit 1
fi

# Define the input and output directories
#fastp_dir="/ddnB/work/kvigil/onr.raw.data.sup.trim/rawdata/reports/fastp_out"
nanoplot_dir="/ddnB/work/kvigil/vibrio_051424/20240514_1438_P2S-01216-B_PAS53473_fe1ca469/sup/nanoplot_out"
output_dir="/ddnB/work/kvigil/vibrio_051424/20240514_1438_P2S-01216-B_PAS53473_fe1ca469/sup/nanoplot_out/multiqc_out"

# Ensure the output directory exists
mkdir -p "${output_dir}"

## Run MultiQC
multiqc "${nanoplot_dir}" -o "${output_dir}"

# Check if MultiQC ran successfully
if [[ $? -ne 0 ]]; then
    echo "Error: MultiQC execution failed"
    exit 1
fi

echo "MultiQC analysis completed successfully"
