#!/bin/bash
#SBATCH --job-name=diamond_all
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=64
#SBATCH --time=7-00:00:00
#SBATCH --output=slurm-%j.out-%N
#SBATCH --error=slurm-%j.err-%N
#SBATCH --account=loni_virus24      # your account name
#SBATCH --partition=single           # the partition

# Load Conda environment (if not already loaded)
module load conda

# Activate diamond-env
source activate diamond_env

# Set the output directory
output_directory="/ddnB/work/kvigil/onr.raw.data.sup.trim/rawdata/minimap2_fastq/diamond_out"

# Create the output directory if it doesn't exist
mkdir -p "$output_directory"

# Run DIAMOND on each input fasta file that contains 'without_blank' in its name
for file in /ddnB/work/kvigil/onr.raw.data.sup.trim/rawdata/minimap2_fastq/minimap2_fasta/*without_blank.fasta; do
    base=$(basename "$file" .fasta)
    output_file="${output_directory}/${base}.tsv"
    diamond blastx -d /work/kvigil/diamond/viralprotein.050124.dmnd -q "$file" -o "$output_file" --sensitive -F 15 --range-culling --top 10 --outfmt 6 qseqid qlen sseqid pident length mismatch evalue bitscore staxids sscinames sskingdoms skingdoms sphylums stitle
done