#!/bin/bash
#SBATCH -A loni_virus24    ### Allocation name
#SBATCH -p single ## queue name
#SBATCH -t 1-00:00:00 ## wall time
#SBATCH -N 1 ## number of nodes
##SBATCH -n 1 ## number of tasks
#SBATCH -c 8 ## number of cores per task
#SBATCH --output=slurm-%j.out-%N
#SBATCH --error=slurm-%j.err-%N
#SBATCH -J nanoplot_all ## job name

##activate conda
module load conda


# Load the Nanoplot module
conda activate nanoplot-env

##NanoPlot 1.32.1 version

# Define the directory containing FASTQ files
fastq_dir="/ddnB/work/kvigil/vibrio_051424/20240514_1438_P2S-01216-B_PAS53473_fe1ca469/fastq_pass/concatenate"

# Define the output directory for Nanoplot results
output_dir="/ddnB/work/kvigil/vibrio_051424/20240514_1438_P2S-01216-B_PAS53473_fe1ca469/fastq_pass/nanoplot_out"

# Create the Nanoplot results directory if it doesn't exist
mkdir -p "$output_dir"

# Iterate over all FASTQ files in the directory
for fastq_file in "${fastq_dir}"/*.fastq.gz; do
    # Check if the current file is a regular file
    if [[ -f "$fastq_file" ]]; then
        # Run Nanoplot on the current FASTQ file
        NanoPlot -t 48 -o "${output_dir}/$(basename ${fastq_file%.fastq})" --fastq "$fastq_file"
    fi
done
