#!/bin/bash
#SBATCH --job-name=seqtk
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=48
#SBATCH --time=1-00:00:00
#SBATCH --output=slurm-%j.out-%N
#SBATCH --error=slurm-%j.err-%N
#SBATCH --account=loni_virus24      # your account name
#SBATCH --partition=single           # the partition

# Load necessary modules if needed
# Example: module load seqtk
# transform all fastq files to fasta files for diamond

# Source directory containing .fastq files
source_dir="/ddnB/work/kvigil/onr.raw.data.sup.trim/rawdata/minimap2_fastq"

# Destination directory for .fasta files
destination_dir="/ddnB/work/kvigil/onr.raw.data.sup.trim/rawdata/minimap2_fastq/minimap2_fasta"

# Create the destination directory if it doesn't exist
mkdir -p "$destination_dir"

# Change directory to where seqtk is located
cd /ddnB/project/awlab/kvigil/scripts/seqtk

# Iterate over all .fastq files in the source directory
for file in "$source_dir"/*.fastq; do
    # Get the base filename without extension
    filename=$(basename "$file" .fastq)

    # Convert .fastq to .fasta using seqtk
    ./seqtk seq -A "$file" > "$destination_dir"/"$filename".fasta

    echo "Converted $filename.fastq to $filename.fasta"
done

echo "Conversion complete."